data = read.table("household_power_consumption.txt",sep=";", header=TRUE)
datas = data[which(data$Date == "1/2/2007" | data$Date == "2/2/2007"), ]
gap = as.numeric(datas$Global_active_power)
grp = as.numeric(datas$Global_reactive_power)
volt = as.numeric(datas$Voltage)
dates = as.Date(datas$Date, "%d/%m/%Y")
times = datas$Time
x = paste(dates, times)
t = strptime(x, "%Y-%m-%d %H:%M:%S")
png("plot4.png",480,480)
par(mfrow = c(2, 2))
plot(t, gap, type="l", ylab = "Global Active Power", xlab = "")
plot(t, volt, type = "l", ylab = "Voltage", xlab = "datetime")
plot(t, sub1, type = "l", ylab = "Energy sub metering", xlab = "")
points(t,sub2, type = "l", col = "red")
points(t, sub3, type = "l", col = "blue")
names = c("Sub_metering_1","Sub_metering_2","Sub_metering_3")
colors = c("black", "red", "blue")
legend("topright", names, lty = 1, col = colors, bty = "n")
plot(t, grp, type="l", ylab = "Global_reactive_power", xlab = "datetime")
dev.off()
