Sys.setlocale("LC_TIME", "English")
data = read.table("household_power_consumption.txt",sep = ";", header = TRUE)
datas = data[which(data$Date == "1/2/2007" | data$Date == "2/2/2007"), ]
sub1 = as.numeric(as.character(datas$Sub_metering_1))
sub2 = as.numeric(as.character(datas$Sub_metering_2))
sub3 = as.numeric(datas$Sub_metering_3)
dates = as.Date(datas$Date, "%d/%m/%Y")
times = datas$Time
x = paste(dates, times)
t = strptime(x, "%Y-%m-%d %H:%M:%S")
png("plot3.png",480,480)
plot(t, sub1, type = "l", ylab = "Energy sub metering", xlab = "")
points(t,sub2, type = "l", col = "red")
points(t, sub3, type = "l", col = "blue")
names = c("Sub_metering_1","Sub_metering_2","Sub_metering_3")
colors = c("black", "red", "blue")
legend("topright", names, lty = 1, col = colors)
dev.off()